### ISSUE TITLE
`game.state.start` can take other parameters, which this hijacks

### ISSUE THREAD

**Issue by hilts-vaughan** [cristianbote/phaser-state-transition#24]
... specifically, being able to pass context to other states. Is it possible to forward these to Phaser still through some optional options?

**Comment by cristianbote** [comment]
Sure thing!
It was on my list of things to be 'normalized' but, since I'm not a day-to-day Phaser user it's hard to grasp that this was needed. Almost any scenario, that has a state with params being passed along, in my opinion, is prone to errors. This is because, then you'd basically gonna have a state(phaser state) that doesn't know about the overall application state.

But, since it's being used, I'm gonna add the enhancement, no problemo!

Stay tuned!

**Comment by cristianbote** [comment]
Give it a try and let me know. Cheers!

**Comment by hilts-vaughan** [comment]
Works awesome, thanks!

**Comment by appsolutegeek** [comment]
What do we pass to the two transition optional params ?  null ? or something else, if we don't wish to use them.

**Comment by cristianbote** [comment]
@appsolutegeek Yup, null should work.
